apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kk-payments
  template:
    metadata:
      labels:
        app: kk-payments
    spec:
      containers:
        - name: kk-payments
          image: kk-payments:latest
          envFrom:
            - configMapRef:
                name: kk-payments-config
